# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-07 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshmaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshmaster.User')),
            ],
        ),
        migrations.CreateModel(
            name='Nightclub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_genre', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=400)),
                ('location', models.CharField(max_length=400)),
                ('average_score', models.CharField(max_length=10)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshmaster.Image')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='nightclub',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='seshmaster.Nightclub'),
            preserve_default=False,
        ),
    ]
