# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshmaster', '0004_auto_20190318_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightclub',
            name='img',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='seshmaster.Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nightclub',
            name='name',
            field=models.CharField(default=0, help_text='Please enter the location name.', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nightclub',
            name='description',
            field=models.CharField(help_text='Little inside on what the place is like ;)', max_length=400),
        ),
        migrations.AlterField(
            model_name='nightclub',
            name='location',
            field=models.CharField(help_text='Where can people find this?', max_length=128),
        ),
        migrations.AlterField(
            model_name='nightclub',
            name='music_genre',
            field=models.CharField(help_text='What is the music like here?', max_length=100),
        ),
        migrations.AlterField(
            model_name='nightclub',
            name='price',
            field=models.CharField(help_text='Price range?', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(help_text='How can we contact you?', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='How should we call you?', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='enter password', max_length=128),
        ),
    ]
