# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshmaster', '0007_auto_20190318_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nightclub',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='seshmaster.Nightclub'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nightclub',
            name='average_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(),
        ),
    ]
