# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshmaster', '0008_auto_20190319_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightclub',
            name='img',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
