# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshmaster', '0009_nightclub_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='nightclub',
        ),
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.CharField(default=0, help_text='Feel free to rant ;)', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(help_text='leave a score from 0-5'),
        ),
    ]
