# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshmaster', '0010_auto_20190320_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightclub',
            name='average_score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(help_text='feel free to rant :)', max_length=400),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(help_text='score from 0-5'),
        ),
    ]
