# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshmaster', '0011_auto_20190321_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightclub',
            name='average_score',
            field=models.IntegerField(null=True),
        ),
    ]
